### ISSUE TITLE
Homekit can not connect to Homey after PTP

### ISSUE THREAD

**Issue by fvhuizen** [swttt/com.swttt.homekit#5] opened 2017-08-08 06:23 UTC
What is your Homey version (Settings → System)?

Versie: 1.5.0-rc.2

What did you try to achieve?

Because of a KaKu issue i needed to restart Homey by PTP

What was the result?

When Homey was online again it was not possible anymore to use Homekit on tablet or phone, because it was not connected to Homey anymore. All devices are visible but no connections.
Also a restart from the app at the settings did not give a solution.

What did you expect as result?

Homekit available

Any other remarks

n.b.

Please attach a Homey System log (Settings -> System -> Send Log)

E6E7D0DB19

**Comment by swttt** [comment] 2017-08-08 08:31
Might have an idea of what the issue might be.
Will try to fix it in the next release..

**Comment by fvhuizen** [comment] 2017-08-08 08:35
Hmmm so meanwhile i can't use it anymore :-(

**Comment by swttt** [comment] 2017-08-08 09:53
You could by re-installing again.

**Comment by fvhuizen** [comment] 2017-08-08 09:57
I will wait for the release (or stable version) and delete the app until its working like it needs to be. But thank you so far.

**Comment by swttt** [comment] 2017-08-08 11:45
How long did you waited after the PTP?
I just tried to reproduce, but it isn't the issue like i assumed..

**Comment by fvhuizen** [comment] 2017-08-08 12:07
I PTP yesterday evening and today a restart from the app without any progress

**Comment by swttt** [comment] 2017-08-15 11:21
Enabled TCP debugging in the next release. The logs will get flooded tho, but lets hope we can see where it stops :)

**Comment by swttt** [comment] 2017-08-18 11:37
Well the flooded logs weren't a good idea, so disabled them again.

But i think the current version fixes the issue, can you let me know?

**Comment by philsniff** [comment] 2017-08-26 22:27
i amon version 1.0.8 and my homeykit has lost all connections since last firmware update (rc.9). perhaps there was an ptp once before the update.

so i don't konw if the firmeware update or the ptp was resulting in this behaviour. but know enen the restart or enable/disable the app won't fix the lost connection to hemekit. all devices incl. homey are marked "no answer" and a "!".

**Comment by swttt** [comment] 2017-08-28 14:54
Huhm...thought it happened to myself as well. But just worked after clicking a device and wait 5 min.
Haven't heard any issues yet since the last beta.
You are sure the app wasn't killed for some reason? (or crashed)

**Comment by TonD83** [comment] 2017-09-23 14:48
Happened to me too, lost connection to Homey(Kit) after pulling the plug (trying to solve another unrelated problem). Never came back :( Any suggestions?

**Comment by moekdegroot** [comment] 2017-09-23 14:58
I auto-restart homeykit 5 min after homey started up. 
Works perfect for me.

**Comment by TonD83** [comment] 2017-09-23 15:07
Thanks, but I restarted HomeyKit several times (of course) but it's just not working anymore. Logging not providing any useful information to debug the problem.

**Comment by swttt** [comment] 2017-10-05 23:50
Please try version 1.0.11 and let me know if the issue still exists.

**Comment by swttt** [comment] 2017-11-12 23:37
Should be fixed in the current beta (still unpublished tho)

**Closed by swttt** 2017-11-12 23:37 UTC
Labels: bug
