### ISSUE TITLE
Dimming glitch

### ISSUE THREAD

**Issue by addwindtan** [swttt/com.swttt.homekit#50] opened 2017-12-02 13:04 UTC
Please see attached video. When dimming by pulling up or down the lever, the dimming % sometimes resets to a different level instead of the final value.

[HomeyKit.zip](https://github.com/swttt/com.swttt.homekit/files/1523815/HomeyKit.zip)

**Comment by robertklep** [comment] 2017-12-09 20:22
@addwindtan what's the hardware (brand, type) of the device that you're dimming?

**Comment by swttt** [comment] 2017-12-09 20:34
Might be because of the failing debouncer.
Still need to add that but lack the spare time for it...

**Comment by addwindtan** [comment] 2017-12-10 02:38
@robertklep it’s a Fibaro Dimmer 2

@swttt that’s what I’m thinking too. Maybe you can point me in the right direction so that I can make the change on the codes

**Comment by swttt** [comment] 2017-12-10 08:29
The problem is that when using the dim slider every change gets pushed to the API and will create a realtime event. So i actually think we should debounce both..

**Comment by markob100** [comment] 2018-02-13 15:13
I have the same issue, also with Fibaro Dimmer 2. Doesn't happen with the Zigbee app controlling a Hue light (not via the Hue hub - direct from Homey on the non-Athom app).

**Comment by swttt** [comment] 2018-02-13 16:37
Nah, it's something i need to add to the code.

Like explained above: moving the slider creates an api request on every percentage (== floods homey).
So i still need to debounce it, then it should act normally.

**Comment by MagnusPer** [comment] 2019-01-17 18:38
Any progress on this ?? ` (HomeyKit v3.0.1 installed on Homey v2.0)`

When I installed version 2.0 in Homey I changed from HomeKit (by Spurt 1) to this app. I observing the same issue with the dimmer slider that go back for all my Fibaro Dimmer 2 devices. The HomeKit app didn´t have this behaviour so the answer may be within that code?

**Comment by robertklep** [comment] 2019-01-17 18:53
No progress on this, but will try to reproduce with my own Fibaro Dimmer 2.

**Comment by jonkoay** [comment] 2019-01-31 08:15
I have the same dimming problem with my Aeotec nano dimmers as described by others. Used to be working fine when using HomeKit (by Sprut 1). Switched to HomeyKit because of Homey 2.0 and have been experiencing this problem.

**Comment by robertklep** [comment] 2019-01-31 08:46
Haven't been able to reproduce it myself, but I'm still on v1.5.

**Comment by jonkoay** [comment] 2019-01-31 10:21
Is there anyway I could help? I’ve just created the diagnostic report:
93866f71-a6f9-4374-bfb8-10948022a498

Not sure if this is useful.

**Comment by robertklep** [comment] 2019-01-31 10:40
I just noticed that the v2 version of the app doesn't debounce realtime events. I'm not running v2 yet, so have to test with the v1.5 branch, and that _does_ have the debouncer, so that would explain why I can't reproduce the problem. I'll try and add the debouncer to the v2 app.

**Comment by robertklep** [comment] 2019-02-02 19:53
If anyone wants to test, I just pushed the `beta` branch that (hopefully) contains a fix for this problem. Requires a CLI install if you want to test it (if you don't know what that is, don't worry, we'll publish the beta through the app store soon).

**Comment by jonkoay** [comment] 2019-02-03 22:54
Happy to test it. Will wait for the beta in the App Store.

**Comment by robertklep** [comment] 2019-02-07 11:18
Please try with 3.0.5 (current stable) or 3.0.6 (current beta).

**Comment by jonkoay** [comment] 2019-02-10 06:43
I’ve waited but 3.0.5 is still not available on the App Store and it is not
automatically installed.

**Comment by robertklep** [comment] 2019-02-10 08:50
Yeah sorry, 3.0.5 was never released, current stable is 3.0.4 and current beta (which should fix this problem) is 3.0.6.

**Comment by macca73** [comment] 2019-02-12 09:53
Hi - just thought I’d make a comment about my Aeotec dimmers also not working.  But I have good news.  Beta 3.0.6 has returned dimming via Apple HomeKit app.  Thanks so much.

**Comment by jonkoay** [comment] 2019-02-12 09:58
Thanks for confirming this. I’m waiting for 3.0.6 to be released as Stable
so that it’s auto-installed by Homey.

**Comment by jonkoay** [comment] 2019-02-14 23:10
Yes, my Homey has finally updated to 3.0.6 and it has fixed the light
dimming problem. Rob, thanks for fixing this issue quickly, really
appreciate it.

**Closed** 2019-02-15 08:47 UTC
