### ISSUE TITLE
[1.0.4]HomeyKit Crashed and won't restart

### ISSUE THREAD

**Issue by andreasbeck** [swttt/com.swttt.homekit#9] opened 2017-08-10 10:00 UTC
After adding several Hue Motion Sensors to HomeyKit the app crashes and can't be restarted.
Here is the log:
Stack trace:

/node_modules/has-node/src/TCP.js:178
var socketID = (currentLine.split(':')[1]).trim();
^

TypeError: Cannot read property 'trim' of undefined
at Socket.<anonymous> (/node_modules/has-node/src/TCP.js:178:55)
at emitOne (events.js:115:13)
at Socket.emit (events.js:210:7)
at addChunk (_stream_readable.js:252:12)
at readableAddChunk (_stream_readable.js:239:11)
at Socket.Readable.push (_stream_readable.js:197:10)
at TCP.onread (net.js:589:20)

Exit code: 1
Exit signal: null

Best Regards 
Andreas

**Comment by swttt** [comment] 2017-08-13 07:51
I think i know whats the cause, will try to fix in 1.0.5.

**Comment by andreasbeck** [comment] 2017-08-13 08:23
Hello,

Thank you also for this.

Best Regards
Andreas

**Comment by swttt** [comment] 2017-08-15 11:23
Huhm...enabled TCP debugging to check other issues as well.
Not sure if current version fixes this tho, but let me know.

**Comment by swttt** [comment] 2017-08-18 11:37
Current Beta should fix this.
Can you let me know if it doesn't?

**Comment by swttt** [comment] 2017-08-28 14:51
I'll close this issue, if it still happens feel free to re-open.

**Closed by swttt** 2017-08-28 14:51 UTC
Labels: bug
