### ISSUE TITLE
[1.0.14] Homekit looses connection after a while and only repairing helps

### ISSUE THREAD

**Issue by bm480** [swttt/com.swttt.homekit#33] opened 2017-10-27 09:52 UTC
This happened to me 4 times in a row since I started experimenting with the HomeyKit app. After pairing Homekit with Homey, adding all 40 devices everything worked smooth. I then used the Home app on my iPhone to put each device in the correct room. But after a while (between 1 to 3 hours), the connection to HomeyKit randomly breaks.

Restarting the iPhone, the HomeyKit app and Homey itself would not do anything to make the connection work again. However, after removing/re-adding the HomeyKit app and re-pairing Homekit at least enabled me to continue my experiments.

After some Googling I encountered the following post in the Homebridge forum: https://github.com/nfarina/homebridge/issues/11#issuecomment-140371310

It seems that Homekit flags badly behaving accessories, disallowing any communication with the device afterwards. Sending out of bound values for characteristics is seen as bad behaviour and this could be the cause of the issue of loosing connection. Checking characteristic values before sending them to Homekit could prevent this from happening.

In the meantime, I will continue my experiments and start with a fresh install, re-pair Homekit and only add some of my most simple devices (no characteristic values that could cause trouble). I will let you know if this enables me to enjoy Homekit integration a little while longer...

**Comment by swttt** [comment] 2017-10-27 12:14
Good find, where i actually use has-node now instead of hap-nodejs (wich is used in homebridge).
Values are checked, and can't reproduce your issue.

Where i do think hap-nodejs is more stable, and will replace has-node in a next release (when i finally find time again)

**Comment by bm480** [comment] 2017-10-31 14:38
So far so good, Homekit still running as smooth as it can be. However, I'm a little cautious adding my Fibaro devices because sensor readings might cause trouble. I've added an Aotec motion sensor instead, to see if that works.

**Comment by swttt** [comment] 2017-11-12 23:35
Have been working for a while on the current beta.
Got all my devices added, and never ran into issues where it didn't came back alive.

So my guess its fixed in the current alpha and beta.

**Closed** 2017-11-12 23:38 UTC
Labels: bug, enhancement

**Comment by bm480** [comment] 2017-11-13 13:31
That is good news. Because this morning I walked into a broken HomeKit connection again, I will try installing the beta tonight to see if this resolves the issue.

**Comment by swttt** [comment] 2017-11-13 14:35
Beta is still awaiting aproval tho or you need to install using the CLI

**Comment by bm480** [comment] 2017-11-14 09:22
All my devices have been added and no connection or pairing issues encountered. 👍 

But I miss the ability to be able to choose which devices are made available to HomeKit. I read about functionality to do this on a zone by zone basis, which would be great I think. Thanks for the great app, I'm very tempted to give a donation...
