### ISSUE TITLE
Device State Not Updated in HomeKit

### ISSUE THREAD

**Issue by Veldkornet** [swttt/com.swttt.homekit#137] opened 2019-02-06 23:35 UTC
HomeyKit v3.0.4
Homey v2.0.2

My device states are not being updated in HomeyKit. 

For example, if a flow turned off a light, the light should be turned off in HomeKit too... but it’s not. 
The device still shows as being on. You then need to “turn it off” (which does nothing), and then you can turn it back on as usual.

**Comment by robertklep** [comment] 2019-02-07 08:38
Does this happen for all of your devices, or for a specific device? If so, what type of device is it?

**Comment by Veldkornet** [comment] 2019-02-07 09:14
Well at the moment I see the issue with my lights which are Fribaro.
They are Fibaro Dimmer 2's, as well as Fibaro Wall Plug 2's.

I'll double check the other items/products, but almost all of my items are Fibaro.

**Comment by robertklep** [comment] 2019-02-07 09:23
Must be v2 related, because my Fibaro Dimmer 2 works as expected in Homekit using v1.5.

I assume that the state of the devices in the Homey app is being updated properly? Also, you could try and test the current beta (v3.0.6) to see if that works better.

**Comment by Veldkornet** [comment] 2019-02-07 09:24
In Homey they look to be okay indeed. I'll try 3.0.6 and let you know.

**Comment by Veldkornet** [comment] 2019-02-10 17:40
Yup, same issue in 3.0.6. 

I tried to look in the log, but the whole thing is empty.

**Comment by robertklep** [comment] 2019-02-10 17:58
The log isn't actually implemented. I'll remove it from the settings page as it confuses people.

As for the state not updating: no idea why it doesn't work. I know that there are some issues with the Fibaro app itself, but I cannot definitively say that that's the cause of your problems.

@nhassink, do you have Fibaro devices?

**Comment by Veldkornet** [comment] 2019-02-10 18:09
This won’t help identify the issue, but I don’t recall having the issue when I was using the Homey “built-in experimental HomeKit app”.

**Comment by robertklep** [comment] 2019-02-10 18:16
You should be able to run both Homeykit and the built-in HK app simultaneously (each providing a separate "Woning"), if you want to check if it still works there.

**Comment by nhassink** [comment] 2019-02-10 18:17
@robertklep nope sorry no fibaro here

**Comment by Veldkornet** [comment] 2019-02-11 08:43
Well, I was using the “built-in” one for a while and I never noticed it (since 2.0.0 came out). It was the first thing I noticed after switched to this one.

**Comment by robertklep** [comment] 2019-02-11 08:55
Since it's not inherent to Homeykit that this shouldn't work, we have to rule things out.

If it _currently_ works with the built-in experimental HK version in your situation, but it doesn't in Homeykit, it's likely something on our end. If it also doesn't work with the experimental app, it could be something in the Fibaro app.

I'm not on v2, @nhassink doesn't have Fibaro devices, so our ability to replicate your problems are limited.

**Comment by Veldkornet** [comment] 2019-02-24 22:39
Well, I can tell you that it’s not specific to Fibaro. I have the same issue with my Zipato lights, Netatmo devices, Rituals, Toon, everything as far as I can tell. 
Control wise, you can still turn everything off and on, but the states are never updated. Temperatures never updated.  Alarms not updated.

**Comment by Veldkornet** [comment] 2019-02-25 08:05
The problem doesn’t happen with the “built-in” one, however that one does not have all of the device types etc and just blindly adds all of my devices, otherwise I would have used it.

**Comment by robertklep** [comment] 2019-02-25 08:10
In that case, all I can suggest is to do a reset (remove the Homey "woning" from iOS, and tap _"Clear HomeKit storage and start over"_ on the settings page).

States not being updated isn't an issue that happens for other users (at least, that I know of), so there's not much that we can debug on our end.

**Comment by Veldkornet** [comment] 2019-02-25 18:47
It does seem to work initially... I have the feeling that it semi-dies somewhere along the way...

**Comment by robertklep** [comment] 2019-02-25 18:48
If it does, I would suspect a Homey-core issue. When it happens next time, try and see if your Homey is using a large amount of memory. There have been issues with people seeing the Homey "app" itself taking up more and more memory, until things start failing and a reboot is required.

**Comment by Veldkornet** [comment] 2019-02-26 23:10
Well I don’t know what’s normal for memory, but this is how it was when the issue started again. Just restarting the HomeKit app seems to fix it though. 
![25fb47af-31d2-4b00-b954-a3d7658d7415](https://user-images.githubusercontent.com/10297361/53453303-fb8b7d80-3a23-11e9-9705-8ec1279f54b7.jpeg)

**Comment by robertklep** [comment] 2019-02-27 07:25
That memory usage seems acceptable to me.

More importantly, I had assumed that the states were _never_ updated for you, but now I understand that you can fix that by restarting the Homeykit app? Does that mean that it works for a while and _then_ stops working?

If that's the case: do you reboot your Homey often?

**Comment by Veldkornet** [comment] 2019-02-27 07:33
Correct, it does initially work, but stops after a while. Restarting the HomeyKit app seems to fix it for a while. 

I hardly ever reboot Homey, unless it installs an update.

**Comment by robertklep** [comment] 2019-02-27 08:08
If it stops working, it suggests that Homey's realtime updates stop working for some reason. Once I get my Homey back, I'll have to look into that a bit closer.

**Comment by Veldkornet** [comment] 2019-03-26 09:03
Any chance you've been able to have a look in more detail yet?

**Comment by robertklep** [comment] 2019-03-26 09:06
No, even though I got my Homey back it's not doing much because I moved all of my home automation to Home Assistant. Not sure when (/if) I'll reinstate my Homey.

**Comment by Veldkornet** [comment] 2019-03-26 09:31
I will install it via CLI and see what pops up in the error logs

**Comment by Veldkornet** [comment] 2019-03-29 08:31
Seems t be a bit of a pain getting the logs.... My Athom CLI seems to quit after about a day running with:
`✖ Connection has been lost, exiting...`
Which is too short to reproduce the error..... will keep trying....

**Comment by robertklep** [comment] 2019-03-29 08:46
I occasionally have the same problem, the CLI connection just gets dropped. With other apps too, so unrelated to Homeykit.

**Comment by Veldkornet** [comment] 2019-03-29 08:47
I understand, I'm just saying, it will therefore take some time to try find anything in the logs :)

**Comment by Veldkornet** [comment] 2019-03-29 10:44
Coincidentally, I now have the issue again.

In the logs for HomeyKit, I don't see any errors or anything. It just stops registering state changes... not for specific devices, but for all devices...

Turning the devices off/on in HomeKit still work, but even these are not shown in the log anymore.

**Comment by robertklep** [comment] 2019-03-29 12:14
So it stops logging _"State Change - ..."_?

That would mean that Homey's core stops sending state change events, which is rather worrisome.

**Comment by Veldkornet** [comment] 2019-03-29 12:22
Correct, it stops logging "_State Change - ..._"
Restarting the app seems to fix it (i don't restart Homey)

**Comment by robertklep** [comment] 2019-03-29 20:35
@Veldkornet when the state changes stop being logged, does it happen randomly? Or does it only happen when you make changes to Homey (specifically, adding or deleting apps or devices)?

**Comment by Veldkornet** [comment] 2019-03-29 21:13
It just happens randomly, there’s no changes to devices etc that’s happening. 

What I saw today, is that it logged that I opened a door, but it didn’t log closing it a few seconds later or anything after.

**Comment by robertklep** [comment] 2019-03-30 07:54
Is that repeatable?

**Comment by Veldkornet** [comment] 2019-03-30 08:01
Well, I haven’t figured out anything specific to trigger it, but it usually happens within a day or so of usage. Although I’ve seen that it could sometimes take a bit longer.

**Comment by Veldkornet** [comment] 2019-03-30 21:11
After some testing today, my felling is that once the problem starts, even though restarting the app fixes it temporarily, it seems to occur more quickly after the app restart. 

I may even say that it just keeps getting worse. A reboot of Homey seems to keep the problem away for longer...

So it may indeed be something Homey related...

**Comment by Veldkornet** [comment] 2019-04-01 20:12
Andy ideas on where to look? Otherwise maybe an option for a “debug build” with a bunch of extra logging for that part?

**Comment by robertklep** [comment] 2019-04-02 07:22
If the realtime updates stop working, there's not much to log. The updates themselves are all logged already, and we can't add additional logging inside Homey core.

**Comment by Veldkornet** [comment] 2019-04-03 19:54
Is it normal for the memory usage by the app to jump up and down by so much?

![6989E542-16B8-4B95-8AA1-32DF9193129A](https://user-images.githubusercontent.com/10297361/55508817-f214b700-565a-11e9-9128-c57cd3980a8a.jpeg)

**Comment by robertklep** [comment] 2019-04-04 07:58
It's not excessive, and the garbage collector kicks in periodically to clean up unused memory.

**Comment by Veldkornet** [comment] 2019-04-25 17:09
I checked today in the Heimdall app, and I saw there that it was still seeing the state changes for devices. 

I know it not quite the same as a HomeKit app, but at least it shows that apps are still able to see the state changes of devices in Homey.

**Comment by robertklep** [comment] 2019-04-25 17:11
I can't debug Homey's core. If it stops sending realtime updates for some reason, there's not much I can do about that.

**Comment by Veldkornet** [comment] 2019-05-01 13:39
I understand what you're saying. But why does the [Heimdall](https://github.com/daneedk/com.uc.heimdall) app see these changes?

Surely if Homey stopped sending the updates, then [Heimdall](https://github.com/daneedk/com.uc.heimdall) would have the same issue?

**Comment by robertklep** [comment] 2019-05-01 13:46
Each app runs in a separate process, with a separate set of communication channels to Homey. After restarting Homeykit, it starts working again because it's a new process with a new set of comm channels.

From an app developer standpoint, it doesn't make sense that without doing anything, Homey's core suddenly decides to stop sending realtime events. I have no idea what could be causing this, nor do I have any possibilities to debug this problem other than logging when a realtime event is received. When those stop being received, I can't dig any further.

**Comment by Veldkornet** [comment] 2019-05-06 05:26
It appears as though I’ve fixed it! Or at the very least, this is the longest its run in a long time without breaking. Usually it broke within a day, now it's been running for a couple of days already without any issues.

I downloaded the current beta version, updated the athom-api in the app from version 2.1.140 -> 2.1.179 and installed the app via cli.
Since then, I've not experienced any issues.

**Comment by robertklep** [comment] 2019-05-06 06:26
That's an interesting find! Any reason why you're using 2.1.179 and not the latest (2.1.185)?

**Comment by Veldkornet** [comment] 2019-05-06 06:34
Only because I didn’t know where to download it from, and 2.1.179 was easy to find from another app :-P

So I have no idea what the changelog is even. But I’m happy to test with the latest if you put it in the beta.

**Comment by robertklep** [comment] 2019-05-06 06:45
The app actually crashes immediately with 2.1.185 😖 so I'll use 2.1.179 as well, will try and upload a beta today.

**Comment by robertklep** [comment] 2019-05-08 07:44
I just published v3.0.11 as a beta on the Homey app store.

**Comment by Veldkornet** [comment] 2019-05-08 08:37
Great! The app was still running without any issues, and I've now installed the beta.

I'll confirm in a couple of days if it still looks good now in the beta.

**Comment by Veldkornet** [comment] 2019-05-13 17:00
Still running since last week without any issues FYI

Looks to be resolved.

**Comment by robertklep** [comment] 2019-05-14 06:03
Great! There are a few other issues popping up, but I'm not sure if they are related to the beta, or to the recently updated Homey firmware. In any case, I'll close this issue as resolved.

Thanks again for your patience and help!

**Closed by robertklep** 2019-05-14 06:03 UTC

**Comment by Veldkornet** [comment] 2019-05-14 08:32
Hmm oki, well for me anyway it's running great now! No issues that I've noticed anyway, thanks! :)

No issues for me with versions:
Homey v2.1.2
HomeyKit v3.0.11 - 08.05.19
