### ISSUE TITLE
Homekit isn't able to control colors on Milights

### ISSUE THREAD

**Issue by ljsvv** [swttt/com.swttt.homekit#6] opened 2017-08-08 06:59 UTC
What is your Homey version (Settings → System)?

Versie: 1.5.0-rc.2

What did you try to achieve?

Control colors of my Mi-lights with Homekit

What was the result?

I can only choose brightness

What did you expect as result?

Like the Hue lights, being able to change colors.

Any other remarks

The log do tell the lights are in color mode.

**Comment by swttt** [comment] 2017-08-08 08:33
Strange behaviour, will look into this.
Could you post 1 log line here from a realtime update?

**Comment by ljsvv** [comment] 2017-08-08 08:36
![naamloos](https://user-images.githubusercontent.com/29465686/29063295-72f18752-7c25-11e7-8530-87e506323fda.png)

**Comment by ljsvv** [comment] 2017-08-08 08:42
![naamloos2](https://user-images.githubusercontent.com/29465686/29063471-4a8cba6a-7c26-11e7-9d9b-2e497dc3ae36.png)

This is a screenshot when I change a color in Homey.

**Comment by ljsvv** [comment] 2017-08-08 08:45
![img_3098](https://user-images.githubusercontent.com/29465686/29063584-a14f561e-7c26-11e7-8c9b-ff5fb725fd65.PNG)

And last but not least, a screenshot from the iOS Home app, only showing brightness

**Comment by swttt** [comment] 2017-08-15 11:20
This might have to do with the fact that you tried adding the light after it was in temperature mode.
Try to switch the lights to a color and add again.

Let me know if i was correct :)

**Comment by ljsvv** [comment] 2017-08-15 13:09
Unfortunately, without succes: 
![1](https://user-images.githubusercontent.com/29465686/29317317-a3c007ae-81cb-11e7-9beb-afb2674f0102.png)
![2](https://user-images.githubusercontent.com/29465686/29317319-a6dc59d8-81cb-11e7-8255-249751b50e16.png)
![3](https://user-images.githubusercontent.com/29465686/29317322-aa172704-81cb-11e7-9201-c085cf64c7f6.png)
![4](https://user-images.githubusercontent.com/29465686/29317324-ace52ee0-81cb-11e7-91ba-da59ac6c3b44.png)
![5](https://user-images.githubusercontent.com/29465686/29317336-bcf8ffaa-81cb-11e7-846a-fcbebd2daf94.JPG)

**Comment by swttt** [comment] 2017-08-18 11:23
Got some Ikea spots yesterday with only color tem... so will try this weekend.

**Comment by RobinBol** [comment] 2017-09-30 11:46
This is probably caused by the fact that the Milights have only light_hue and not light_saturation capability. I've encountered the same issue with my Milights and fixed it with this PR (https://github.com/swttt/com.swttt.homekit/pull/27).

**Comment by swttt** [comment] 2017-10-05 20:05
PR is merged, this should be fixed now.
If now, please let me know and reopen this issue.

**Closed by swttt** 2017-10-05 20:05 UTC
Labels: bug
