### ISSUE TITLE
No Sensors can added

### ISSUE THREAD

**Issue by Strike2001** [swttt/com.swttt.homekit#107] opened 2019-01-04 18:01 UTC
Any Sensor device i add with Virtual Devices App are not added to homekit self or  device overview settings from the app.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robertklep** [comment] 2019-01-04 18:02
Can you provide a specific example?

**Comment by nhassink** [comment] 2019-01-04 19:50
i can reproduce your problem. Will try to find a solution

**Comment by nhassink** [comment] 2019-01-04 20:49
The problem seems to be with the virtual devices app not being totally v2 ready yet. This should be fixed with a v2 version of the virtual devices app

**Comment by nhassink** [comment] 2019-01-06 13:39
Hi, I was wondering if you still have this issue on RC11? I can't reproduce this anymore. With the latest version Im able to add all kinds of sensors using the virtual devices app

**Comment by Strike2001** [comment] 2019-01-07 11:46
~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment] 2019-01-07 11:47
![GitHawk Upload by Strike2001](https://i.imgur.com/3mOeSG3.jpg)![no motionsensor "testi" found by Strike2001](https://i.imgur.com/hms1Ng8.jpg)

homey 2.0.0-rc.11

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nhassink** [comment] 2019-01-07 19:07
also HomeyKit 3.0.1?

**Comment by nhassink** [comment] 2019-01-07 19:08
I have tried to reproduce this by adding a virtual device with the motion capability but it shows up fine here in homekit and in the settings page of homeykit

**Comment by Strike2001** [comment] 2019-01-07 23:53
so i have added some devices and only the virtual device of the category home alarm not working. also not if i try to add a motion sensor with on/off option not available in homekit . is it possible that they not work because heimdall is not installed ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment] 2019-01-08 08:02
the home alarm also shown in homekit when i create a VD   but the motion / alarm contact  not . i has also delete all old VD and try it again but nothing changed , sensor of the categorie home alarm not available in homekit or homekit settings. 
can it be that this sensor settings for example always on is not set or somthing else , because in the settings i can t also add / remove them to HK . all other are visible without the display error before. also scrolling on the page runs .

Von meinem iPhone gesendet

**Comment by nhassink** [comment] 2019-01-08 09:20
can you send a screenshot of developer.athom.com and then from the devices page for the virtual devices you created but that do not show up in homekit? I think the problem is that not all combinations of devices / capabilities are supported by homeykit and that's why they don't show up in settings or in homekit itself.

**Comment by nhassink** [comment] 2019-01-08 09:37
i seem to have found the problem. Seems to be a bug in virtual devices. When you create a virtual homealarm device the homealarm state capability is pre-set in the pairing window. However you have to unselect and then select it again for it to properly register as a homealarm device. When you just ad it the alarmstate capability is not set correctly and then it won't show up in homekit

**Comment by Strike2001** [comment] 2019-01-08 09:41
sure i send you 3 Pic , 2 are the test sensor and the sensor names ich created before homeyupdate and is in homekit visible . 
![alarm_contact test device by Strike2001](https://i.imgur.com/l5GVgdd.jpg)![alarm_motion test device by Strike2001](https://i.imgur.com/hIlKXJR.jpg)![old alarm motion device ( before firmware v2 added) by Strike2001](https://i.imgur.com/Of3LHe5.jpg)

i also found a error by using the tags when i chose the color tag like this example 
![chose per click on it by Strike2001](https://i.imgur.com/TAjAx4z.jpg)![this combination works not longer as before. by Strike2001](https://i.imgur.com/qQ13Bfu.jpg)![that works by Strike2001](https://i.imgur.com/TZiO5hJ.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment] 2019-01-08 09:48
can it be the class is not sensor ? by the devices 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment] 2019-01-08 09:56
![GitHawk Upload by Strike2001](https://i.imgur.com/5NU2V1v.jpg)
this device also as class sensor added and visible in Homekit so i think that the error .
on the BSH app it is also a contact alarm visible in Homekit till now only for the dishwasher . is that class also sensor ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nhassink** [comment] 2019-01-08 10:10
Yes the problem is that you created a virtual device of class Homealarm with the capability alarm_contact (Door/window test) or alarm_motion (motion Test). This combination is not supported 
You should make a sensor class with the capability alarm_contact or alarm_motion for this. If you want a homealarm device you should select the armed/partially armed/disarmed option (homealarm_state) in virtual devices

**Comment by nhassink** [comment] 2019-01-08 10:17
the only way you can change this is by making a new virtual device, select class sensor and then select the motion or contact capability

**Comment by nhassink** [comment] 2019-01-08 11:02
I see what you mean. In the last version of virtual devices it is not possible anymore to add a motion or a contact sensor ... 

Maybe you can ask this to the virtual device developer or use the older (Stable) version of the virtual devices app.

**Comment by Strike2001** [comment] 2019-01-08 11:03
i must correct me now after i edit the capabilities.js of virtual devices and added these to the sensor section too . it works . can t wait till 0.8.4 🤣

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment] 2019-01-08 11:03
![GitHawk Upload by Strike2001](https://i.imgur.com/Nw8WjvR.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nhassink** [comment] 2019-01-08 12:02
Ok great

**Closed** 2019-02-07 11:09 UTC
